LAMENES		= main.c lamenes.c lame6502/lame6502.c lame6502/disas.c lame6502/debugger.c lib/str_chrchk.c lib/str_cut.c sdl_functions.c romloader.c ppu.c input.c lib/str_replace.c
CC              = i586-mingw32msvc-gcc
OBJ_FLAG        = -O3 -fomit-frame-pointer -Wall -lmingw32 -lSDLmain -lSDL -mwindows;

lamenes:	$(LAMENES)
		$(CC) $(LAMENES) $(OBJ_FLAG)
		strip a.exe
		mv a.exe lamenes.exe

clean:		$(LAMENES)
		rm -f lamenes.exe lamenes lamenes.core core.*
